// Auto-generated — kode telepon internasional (ISO-2, nama, kode dial).
// Sumber: samayo/country-json. 240 negara. Default = Indonesia (ID/+62).
export const KODE_DEFAULT = "ID";

export const KODE_TELEPON = [
    { iso: "AF", nama: "Afghanistan", dial: "93" },
    { iso: "AL", nama: "Albania", dial: "355" },
    { iso: "DZ", nama: "Algeria", dial: "213" },
    { iso: "AS", nama: "American Samoa", dial: "1684" },
    { iso: "AD", nama: "Andorra", dial: "376" },
    { iso: "AO", nama: "Angola", dial: "244" },
    { iso: "AI", nama: "Anguilla", dial: "1264" },
    { iso: "AQ", nama: "Antarctica", dial: "672" },
    { iso: "AG", nama: "Antigua and Barbuda", dial: "1268" },
    { iso: "AR", nama: "Argentina", dial: "54" },
    { iso: "AM", nama: "Armenia", dial: "374" },
    { iso: "AW", nama: "Aruba", dial: "297" },
    { iso: "AU", nama: "Australia", dial: "61" },
    { iso: "AT", nama: "Austria", dial: "43" },
    { iso: "AZ", nama: "Azerbaijan", dial: "994" },
    { iso: "BS", nama: "Bahamas", dial: "1242" },
    { iso: "BH", nama: "Bahrain", dial: "973" },
    { iso: "BD", nama: "Bangladesh", dial: "880" },
    { iso: "BB", nama: "Barbados", dial: "1246" },
    { iso: "BY", nama: "Belarus", dial: "375" },
    { iso: "BE", nama: "Belgium", dial: "32" },
    { iso: "BZ", nama: "Belize", dial: "501" },
    { iso: "BJ", nama: "Benin", dial: "229" },
    { iso: "BM", nama: "Bermuda", dial: "1441" },
    { iso: "BT", nama: "Bhutan", dial: "975" },
    { iso: "BO", nama: "Bolivia", dial: "591" },
    { iso: "BA", nama: "Bosnia and Herzegovina", dial: "387" },
    { iso: "BW", nama: "Botswana", dial: "267" },
    { iso: "BV", nama: "Bouvet Island", dial: "55" },
    { iso: "BR", nama: "Brazil", dial: "55" },
    { iso: "IO", nama: "British Indian Ocean Territory", dial: "246" },
    { iso: "BN", nama: "Brunei", dial: "673" },
    { iso: "BG", nama: "Bulgaria", dial: "359" },
    { iso: "BF", nama: "Burkina Faso", dial: "226" },
    { iso: "BI", nama: "Burundi", dial: "257" },
    { iso: "KH", nama: "Cambodia", dial: "855" },
    { iso: "CM", nama: "Cameroon", dial: "237" },
    { iso: "CA", nama: "Canada", dial: "1" },
    { iso: "CV", nama: "Cape Verde", dial: "238" },
    { iso: "KY", nama: "Cayman Islands", dial: "1345" },
    { iso: "CF", nama: "Central African Republic", dial: "236" },
    { iso: "TD", nama: "Chad", dial: "235" },
    { iso: "CL", nama: "Chile", dial: "56" },
    { iso: "CN", nama: "China", dial: "86" },
    { iso: "CX", nama: "Christmas Island", dial: "61" },
    { iso: "CC", nama: "Cocos (Keeling) Islands", dial: "61" },
    { iso: "CO", nama: "Colombia", dial: "57" },
    { iso: "KM", nama: "Comoros", dial: "269" },
    { iso: "CG", nama: "Congo", dial: "242" },
    { iso: "CK", nama: "Cook Islands", dial: "682" },
    { iso: "CR", nama: "Costa Rica", dial: "506" },
    { iso: "HR", nama: "Croatia", dial: "385" },
    { iso: "CU", nama: "Cuba", dial: "53" },
    { iso: "CY", nama: "Cyprus", dial: "357" },
    { iso: "CZ", nama: "Czech Republic", dial: "420" },
    { iso: "DK", nama: "Denmark", dial: "45" },
    { iso: "DJ", nama: "Djibouti", dial: "253" },
    { iso: "DM", nama: "Dominica", dial: "1767" },
    { iso: "DO", nama: "Dominican Republic", dial: "1849" },
    { iso: "TP", nama: "East Timor", dial: "670" },
    { iso: "EC", nama: "Ecuador", dial: "593" },
    { iso: "EG", nama: "Egypt", dial: "20" },
    { iso: "SV", nama: "El Salvador", dial: "503" },
    { iso: "GQ", nama: "Equatorial Guinea", dial: "240" },
    { iso: "ER", nama: "Eritrea", dial: "291" },
    { iso: "EE", nama: "Estonia", dial: "372" },
    { iso: "SZ", nama: "Eswatini", dial: "268" },
    { iso: "ET", nama: "Ethiopia", dial: "251" },
    { iso: "FK", nama: "Falkland Islands", dial: "500" },
    { iso: "FO", nama: "Faroe Islands", dial: "298" },
    { iso: "FJ", nama: "Fiji Islands", dial: "679" },
    { iso: "FI", nama: "Finland", dial: "358" },
    { iso: "FR", nama: "France", dial: "33" },
    { iso: "GF", nama: "French Guiana", dial: "594" },
    { iso: "PF", nama: "French Polynesia", dial: "689" },
    { iso: "TF", nama: "French Southern territories", dial: "262" },
    { iso: "GA", nama: "Gabon", dial: "241" },
    { iso: "GM", nama: "Gambia", dial: "220" },
    { iso: "GE", nama: "Georgia", dial: "995" },
    { iso: "DE", nama: "Germany", dial: "49" },
    { iso: "GH", nama: "Ghana", dial: "233" },
    { iso: "GI", nama: "Gibraltar", dial: "350" },
    { iso: "GR", nama: "Greece", dial: "30" },
    { iso: "GL", nama: "Greenland", dial: "299" },
    { iso: "GD", nama: "Grenada", dial: "1473" },
    { iso: "GP", nama: "Guadeloupe", dial: "590" },
    { iso: "GU", nama: "Guam", dial: "1671" },
    { iso: "GT", nama: "Guatemala", dial: "502" },
    { iso: "GN", nama: "Guinea", dial: "224" },
    { iso: "GW", nama: "Guinea-Bissau", dial: "245" },
    { iso: "GY", nama: "Guyana", dial: "592" },
    { iso: "HT", nama: "Haiti", dial: "509" },
    { iso: "HM", nama: "Heard Island and McDonald Islands", dial: "672" },
    { iso: "VA", nama: "Holy See (Vatican City State)", dial: "379" },
    { iso: "HN", nama: "Honduras", dial: "504" },
    { iso: "HK", nama: "Hong Kong", dial: "852" },
    { iso: "HU", nama: "Hungary", dial: "36" },
    { iso: "IS", nama: "Iceland", dial: "354" },
    { iso: "IN", nama: "India", dial: "91" },
    { iso: "ID", nama: "Indonesia", dial: "62" },
    { iso: "IR", nama: "Iran", dial: "98" },
    { iso: "IQ", nama: "Iraq", dial: "964" },
    { iso: "IE", nama: "Ireland", dial: "353" },
    { iso: "IL", nama: "Israel", dial: "972" },
    { iso: "IT", nama: "Italy", dial: "39" },
    { iso: "CI", nama: "Ivory Coast", dial: "225" },
    { iso: "JM", nama: "Jamaica", dial: "1876" },
    { iso: "JP", nama: "Japan", dial: "81" },
    { iso: "JO", nama: "Jordan", dial: "962" },
    { iso: "KZ", nama: "Kazakhstan", dial: "7" },
    { iso: "KE", nama: "Kenya", dial: "254" },
    { iso: "KI", nama: "Kiribati", dial: "686" },
    { iso: "KW", nama: "Kuwait", dial: "965" },
    { iso: "KG", nama: "Kyrgyzstan", dial: "996" },
    { iso: "LA", nama: "Laos", dial: "856" },
    { iso: "LV", nama: "Latvia", dial: "371" },
    { iso: "LB", nama: "Lebanon", dial: "961" },
    { iso: "LS", nama: "Lesotho", dial: "266" },
    { iso: "LR", nama: "Liberia", dial: "231" },
    { iso: "LY", nama: "Libya", dial: "218" },
    { iso: "LI", nama: "Liechtenstein", dial: "423" },
    { iso: "LT", nama: "Lithuania", dial: "370" },
    { iso: "LU", nama: "Luxembourg", dial: "352" },
    { iso: "MO", nama: "Macao", dial: "853" },
    { iso: "MG", nama: "Madagascar", dial: "261" },
    { iso: "MW", nama: "Malawi", dial: "265" },
    { iso: "MY", nama: "Malaysia", dial: "60" },
    { iso: "MV", nama: "Maldives", dial: "960" },
    { iso: "ML", nama: "Mali", dial: "223" },
    { iso: "MT", nama: "Malta", dial: "356" },
    { iso: "MH", nama: "Marshall Islands", dial: "692" },
    { iso: "MQ", nama: "Martinique", dial: "596" },
    { iso: "MR", nama: "Mauritania", dial: "222" },
    { iso: "MU", nama: "Mauritius", dial: "230" },
    { iso: "YT", nama: "Mayotte", dial: "262" },
    { iso: "MX", nama: "Mexico", dial: "52" },
    { iso: "FM", nama: "Micronesia, Federated States of", dial: "691" },
    { iso: "MD", nama: "Moldova", dial: "373" },
    { iso: "MC", nama: "Monaco", dial: "377" },
    { iso: "MN", nama: "Mongolia", dial: "976" },
    { iso: "MS", nama: "Montserrat", dial: "1664" },
    { iso: "MA", nama: "Morocco", dial: "212" },
    { iso: "MZ", nama: "Mozambique", dial: "258" },
    { iso: "MM", nama: "Myanmar", dial: "95" },
    { iso: "NA", nama: "Namibia", dial: "264" },
    { iso: "NR", nama: "Nauru", dial: "674" },
    { iso: "NP", nama: "Nepal", dial: "977" },
    { iso: "NL", nama: "Netherlands", dial: "31" },
    { iso: "AN", nama: "Netherlands Antilles", dial: "599" },
    { iso: "NC", nama: "New Caledonia", dial: "687" },
    { iso: "NZ", nama: "New Zealand", dial: "64" },
    { iso: "NI", nama: "Nicaragua", dial: "505" },
    { iso: "NE", nama: "Niger", dial: "227" },
    { iso: "NG", nama: "Nigeria", dial: "234" },
    { iso: "NU", nama: "Niue", dial: "683" },
    { iso: "NF", nama: "Norfolk Island", dial: "672" },
    { iso: "KP", nama: "North Korea", dial: "850" },
    { iso: "MK", nama: "North Macedonia", dial: "389" },
    { iso: "GB", nama: "Northern Ireland", dial: "44" },
    { iso: "MP", nama: "Northern Mariana Islands", dial: "1670" },
    { iso: "NO", nama: "Norway", dial: "47" },
    { iso: "OM", nama: "Oman", dial: "968" },
    { iso: "PK", nama: "Pakistan", dial: "92" },
    { iso: "PW", nama: "Palau", dial: "680" },
    { iso: "PS", nama: "Palestine", dial: "970" },
    { iso: "PA", nama: "Panama", dial: "507" },
    { iso: "PG", nama: "Papua New Guinea", dial: "675" },
    { iso: "PY", nama: "Paraguay", dial: "595" },
    { iso: "PE", nama: "Peru", dial: "51" },
    { iso: "PH", nama: "Philippines", dial: "63" },
    { iso: "PN", nama: "Pitcairn", dial: "64" },
    { iso: "PL", nama: "Poland", dial: "48" },
    { iso: "PT", nama: "Portugal", dial: "351" },
    { iso: "PR", nama: "Puerto Rico", dial: "1939" },
    { iso: "QA", nama: "Qatar", dial: "974" },
    { iso: "RE", nama: "Reunion", dial: "262" },
    { iso: "RO", nama: "Romania", dial: "40" },
    { iso: "RU", nama: "Russia", dial: "7" },
    { iso: "RW", nama: "Rwanda", dial: "250" },
    { iso: "SH", nama: "Saint Helena", dial: "290" },
    { iso: "KN", nama: "Saint Kitts and Nevis", dial: "1869" },
    { iso: "LC", nama: "Saint Lucia", dial: "1758" },
    { iso: "PM", nama: "Saint Pierre and Miquelon", dial: "508" },
    { iso: "VC", nama: "Saint Vincent and the Grenadines", dial: "1784" },
    { iso: "WS", nama: "Samoa", dial: "685" },
    { iso: "SM", nama: "San Marino", dial: "378" },
    { iso: "ST", nama: "Sao Tome and Principe", dial: "239" },
    { iso: "SA", nama: "Saudi Arabia", dial: "966" },
    { iso: "SN", nama: "Senegal", dial: "221" },
    { iso: "RS", nama: "Serbia", dial: "381" },
    { iso: "SC", nama: "Seychelles", dial: "248" },
    { iso: "SL", nama: "Sierra Leone", dial: "232" },
    { iso: "SG", nama: "Singapore", dial: "65" },
    { iso: "SK", nama: "Slovakia", dial: "421" },
    { iso: "SI", nama: "Slovenia", dial: "386" },
    { iso: "SB", nama: "Solomon Islands", dial: "677" },
    { iso: "SO", nama: "Somalia", dial: "252" },
    { iso: "ZA", nama: "South Africa", dial: "27" },
    { iso: "GS", nama: "South Georgia and the South Sandwich Islands", dial: "500" },
    { iso: "KR", nama: "South Korea", dial: "82" },
    { iso: "SS", nama: "South Sudan", dial: "211" },
    { iso: "ES", nama: "Spain", dial: "34" },
    { iso: "LK", nama: "Sri Lanka", dial: "94" },
    { iso: "SD", nama: "Sudan", dial: "249" },
    { iso: "SR", nama: "Suriname", dial: "597" },
    { iso: "SJ", nama: "Svalbard and Jan Mayen", dial: "47" },
    { iso: "SE", nama: "Sweden", dial: "46" },
    { iso: "CH", nama: "Switzerland", dial: "41" },
    { iso: "SY", nama: "Syria", dial: "963" },
    { iso: "TJ", nama: "Tajikistan", dial: "992" },
    { iso: "TZ", nama: "Tanzania", dial: "255" },
    { iso: "TH", nama: "Thailand", dial: "66" },
    { iso: "CD", nama: "The Democratic Republic of Congo", dial: "243" },
    { iso: "TG", nama: "Togo", dial: "228" },
    { iso: "TK", nama: "Tokelau", dial: "690" },
    { iso: "TO", nama: "Tonga", dial: "676" },
    { iso: "TT", nama: "Trinidad and Tobago", dial: "1868" },
    { iso: "TN", nama: "Tunisia", dial: "216" },
    { iso: "TR", nama: "Turkey", dial: "90" },
    { iso: "TM", nama: "Turkmenistan", dial: "993" },
    { iso: "TC", nama: "Turks and Caicos Islands", dial: "1649" },
    { iso: "TV", nama: "Tuvalu", dial: "688" },
    { iso: "UG", nama: "Uganda", dial: "256" },
    { iso: "UA", nama: "Ukraine", dial: "380" },
    { iso: "AE", nama: "United Arab Emirates", dial: "971" },
    { iso: "UK", nama: "United Kingdom", dial: "44" },
    { iso: "US", nama: "United States", dial: "1" },
    { iso: "UM", nama: "United States Minor Outlying Islands", dial: "1" },
    { iso: "UY", nama: "Uruguay", dial: "598" },
    { iso: "UZ", nama: "Uzbekistan", dial: "998" },
    { iso: "VU", nama: "Vanuatu", dial: "678" },
    { iso: "VE", nama: "Venezuela", dial: "58" },
    { iso: "VN", nama: "Vietnam", dial: "84" },
    { iso: "VG", nama: "Virgin Islands, British", dial: "1" },
    { iso: "VI", nama: "Virgin Islands, U.S.", dial: "1" },
    { iso: "WF", nama: "Wallis and Futuna", dial: "681" },
    { iso: "EH", nama: "Western Sahara", dial: "212" },
    { iso: "YE", nama: "Yemen", dial: "967" },
    { iso: "ZM", nama: "Zambia", dial: "260" },
    { iso: "ZW", nama: "Zimbabwe", dial: "263" },
];

// Cari negara berdasarkan nomor tersimpan: cocokkan prefix dial TERPANJANG dulu
// (mis. "62"812… -> ID). Kembalikan { iso, dial } atau default bila tak cocok.
export function deteksiNegara(nomor) {
    // `\D` (bukan-angka), BUKAN `D`. Garis miringnya pernah hilang, sehingga
    // yang dibuang justru huruf "D" dan tanda baca dibiarkan lolos: "+62 812"
    // tetap diawali "+" dan tak pernah cocok dengan satu pun kode negara,
    // lalu diam-diam jatuh ke Indonesia. Pemanggil satu-satunya kebetulan
    // sudah membersihkan nomornya lebih dulu — jadi cacat ini tak pernah
    // terlihat, dan akan menunggu pemanggil kedua untuk muncul.
    const s = String(nomor || "").replace(/\D/g, "");
    if (!s) return { iso: KODE_DEFAULT, dial: "62" };
    let best = null;
    for (const k of KODE_TELEPON) {
        if (s.startsWith(k.dial) && (!best || k.dial.length > best.dial.length)) best = k;
    }
    return best || { iso: KODE_DEFAULT, dial: "62" };
}
